export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DEDUCT_INGREDIENT = 'DEDUCT_INGREDIENT';
export const SET_INIT_INGREDIENTS = 'SET_INIT_INGREDIENTS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';

export const INIT_ORDER_REQUEST = 'INIT_ORDER_REQUEST';
export const POST_ORDER_REQUEST_START = 'POST_ORDER_REQUEST_START'
export const POST_ORDER_REQUEST_SUCCESS = 'POST_ORDER_REQUEST_SUCCESS';
export const POST_ORDER_REQUEST_FAIL = 'POST_ORDER_REQUEST_FAIL';

export const INIT_GET_ORDERS_REQUEST = 'INIT_GET_ORDERS_REQUEST';
export const GET_ORDERS_REQUEST_START = 'GET_ORDERS_REQUEST_START'
export const GET_ORDERS_REQUEST_SUCCESS = 'GET_ORDERS_REQUEST_SUCCESS';
export const GET_ORDERS_REQUEST_FAIL = 'GET_ORDERS_REQUEST_FAIL';